export class Persona {
  // TU CÓDIGO VA AQUI, NO MODIFIQUES EL NOMBRE DEL ARCHIVO
  // NI TAMPOCO LOS TESTS NI TAMPOCO EL NOMBRE DE LA CLASE
  // PORQUE NO FUNCIONARÁ
}

export class Ingeniero extends Persona {
  // TU CÓDIGO VA AQUI, NO MODIFIQUES EL NOMBRE DEL ARCHIVO
  // NI TAMPOCO LOS TESTS NI TAMPOCO EL NOMBRE DE LA CLASE
  // PORQUE NO FUNCIONARÁ
}

export class IngenieroSobreescrito extends Persona {
  // TU CÓDIGO VA AQUI, NO MODIFIQUES EL NOMBRE DEL ARCHIVO
  // NI TAMPOCO LOS TESTS NI TAMPOCO EL NOMBRE DE LA CLASE
  // PORQUE NO FUNCIONARÁ
}
